services:
  db:
    container_name: postgres
    image: postgres:14.0
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      
  airflow:
    container_name: airflow
    build: 
      context: ./airflow_image
    ports:
     - 8080:8080
    environment:
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./datasets:/opt/airflow/datasets
    depends_on:
      - db
    command: >
     bash -c "airflow db migrate && airflow standalone"

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
     - "9090:9090"
     - "9001:9001"
    environment:
     MINIO_ROOT_USER: minioadmin
     MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
     - ./minio/data:/data
