# ESG Metrics Normalization - Standard Names Configuration
# This file contains all standardized metric names organized by group

STANDARD_NAMES_BY_GROUP = {
    "anti-corruption": [
        "Anti-Corruption Training - Employees",
        "Anti-Corruption Training - Management",
        "Anti-Corruption Training - Directors & Senior Management",
        "Anti-Corruption Training - Relevant Employees",
        "Anti-Corruption Training - Number of Trained Employees",
        "Anti-Corruption Training Completion Rate",
        "Corruption Risk Assessment - Sites",
        "Sites Exposed to Major Corruption Risk - Count",
        "Corruption Cases - Reported",
        "Corruption Cases - Resolved",
        "Corruption Cases - Valid",
        "Corruption Cases - Valid and Resolved",
        "Legal & Regulatory Violations - Anti-Corruption",
        "Employees Receiving Anti-Corruption Training - Count"
    ],
    
    "employee turnover": [
        "Employee Turnover Rate - Total",
        "Employee Turnover Rate - Voluntary",
        "Employee Turnover Rate - Involuntary",
        "Employee Turnover Rate - Women",
        "Employee Turnover Rate - Men",
        "Employee Turnover Rate - Age Under 30",
        "Employee Turnover Rate - Age 30-50",
        "Employee Turnover Rate - Age Over 50",
        "Employee Turnover Rate - Northeast",
        "Employee Turnover Rate - Central-West",
        "Employee Turnover Rate - North",
        "Employee Turnover Rate - Southeast",
        "Employee Turnover Rate - South",
        "Employee Turnover Rate - Management",
        "Employee Turnover Rate - Operational",
        "Employee Turnover Rate - Administrative",
        "Employee Turnover Rate - Coordination/Supervision",
        "Employee Turnover Rate - Apprenticeship",
        "Employee Turnover Rate - Superintendence",
        "Employee Turnover Rate - White",
        "Employee Turnover Rate - Asian",
        "Employee Turnover Rate - Black",
        "Employee Turnover Rate - Indigenous",
        "Employee Turnover Rate - Not Declared",
        "Voluntary Turnover Rate - Total",
        "Voluntary Turnover Rate - Women",
        "Voluntary Turnover Rate - Men",
        "Voluntary Turnover Rate - POC",
        "Voluntary Turnover Rate - <5 Years of Tenure",
        "Voluntary Turnover Rate - Age Under 30",
        "Voluntary Turnover Rate - Age 30-50",
        "Voluntary Turnover Rate - Age Over 50",
        "Voluntary Turnover Rate - Management",
        "Voluntary Turnover Rate - Operational",
        "Voluntary Turnover Rate - Administrative",
        "Voluntary Turnover Rate - Coordination/Supervision",
        "Voluntary Turnover Rate - Apprenticeship",
        "Voluntary Turnover Rate - Superintendence",
        "Voluntary Turnover Rate - White",
        "Voluntary Turnover Rate - Asian",
        "Voluntary Turnover Rate - Black",
        "Voluntary Turnover Rate - Indigenous",
        "Voluntary Turnover Rate - Not Declared",
        "Retention Rate",
        "Retention Rate - Women",
        "Retention Rate - Men",
        "Retention Rate - After Parental Leave",
        "Attrition Rate",
        "Voluntary Attrition Rate",
        "Voluntary Attrition Rate - Women",
        "Voluntary Attrition Rate - Men",
        "Voluntary Attrition Rate - POC",
        "Voluntary Attrition Rate - <5 Years of Tenure"
    ],
    
    "biogenic emissions": [
        "Biogenic Emissions - Total",
        "Biogenic Emissions - Purchased Steam Includes Renewable Sources",
        "Biogenic Emissions - By Energy Type",
        "Biogenic Emissions - CO2 (Metric Tons)",
        "Biogenic Emissions - CH4 (Metric Tons)",
        "Biogenic Emissions - N2O (Metric Tons)"
    ],
    
    "employee training": [
        "Average Training Hours per Employee - Total",
        "Total Training Hours",
        "Average Training Hours per Employee - Female",
        "Average Training Hours per Employee - Male",
        "Average Training Hours per Employee - Under 30",
        "Average Training Hours per Employee - 30-50",
        "Average Training Hours per Employee - Over 50",
        "Average Training Hours per Employee - Front-line Employee",
        "Average Training Hours per Employee - Front-line Management",
        "Average Training Hours per Employee - Middle Management",
        "Average Training Hours per Employee - Senior Management",
        "Number of Participants - Management Training (Leaders)",
        "Number of Participants - Management Training (Managers)"
    ],
    
    "ehs compliance": [
        "EHS Fines",
        "EHS Inspections",
        "Fair Trade Violations",
        "Information Security Violations",
        "Marketing & Labeling Violations"
    ],
    
    "gender diversity": [
        "Female Representation - Overall (%)",
        "Female Representation - Total Workforce (#)",
        "Female Representation - Board of Directors",
        "Female Representation - Executive Council",
        "Female Representation - Executives",
        "Female Representation - Senior Management",
        "Female Representation - Management",
        "Female Representation - Managers",
        "Female Representation - Management and Professional Staff",
        "Female Representation - New Hires (#)",
        "Female Representation - New Hires (%)",
        "Women in Enterprise",
        "Women in Leadership"
    ],
    
    "hazardous waste": [
        "Total Hazardous Waste",
        "Total Non-Hazardous Waste",
        "Hazardous Waste - Disposal/Directed to Disposal",
        "Hazardous Waste - Incineration without Energy Recovery",
        "Hazardous Waste - Incineration with Energy Recovery",
        "Hazardous Waste - Landfill",
        "Hazardous Waste - Other Disposal Methods",
        "Hazardous Waste - Reused",
        "Hazardous Waste - Recovered in Other Ways",
        "Hazardous Waste - Total Reused and Recycled",
        "Non-Hazardous Waste - Disposal/Directed to Disposal",
        "Non-Hazardous Waste - Incineration without Energy Recovery",
        "Non-Hazardous Waste - Incineration with Energy Recovery",
        "Non-Hazardous Waste - Landfill",
        "Non-Hazardous Waste - Other Disposal Methods"
    ],
    
    "independent directors": [
        "Board Independence",
        "Independent Directors - Representation",
        "Number of Independent Directors",
        "Percentage of Independent Directors on Board",
        "Percentage of Independent Directors in Audit Committee",
        "Attendance Rate - Independent Directors at Board Meetings",
        "Attendance Rate - Independent Directors at Audit Committee",
        "Attendance Rate - Independent Directors at Compensation Committee",
        "Attendance Rate - Independent Directors at Candidate Recommendation Committee",
        "Number of Agenda Items Objected/Amended by Independent Directors",
        "Limitations on Other Jobs for Independent Directors",
        "Total Compensation for Independent Directors",
        "Percentage of Non-Independent Directors with Anti-Corruption Training"
    ],
    
    "lost time injury": [
        "Lost Time Injury Rate (LTIR) - Total",
        "Lost Time Injury Rate (LTIR) - Employees Only",
        "Lost Time Injury Rate (LTIR) - Contractors",
        "Lost Time Injury Rate (LTIR) - Combined",
        "Lost Time Injury Rate (LTIR) - U.S. Only",
        "Lost Time Injury Rate (LTIR) - Worldwide",
        "Lost Time Injury Rate (LTIR) - U.S. Courier and Express Delivery",
        "Lost Time Injury Rate (LTIR) - U.S. General Warehousing",
        "Lost Time Injury Frequency Rate (LTIFR)",
        "Number of Lost-Time Injuries (LTI)",
        "Number of Lost-Time Injuries Including Microtraumas",
        "Number of Microtrauma Cases",
        "Accidents at Work",
        "Deaths Resulting from Accidents at Work",
        "Environmental Fines or Penalties"
    ],
    
    "minority representation": [
        "Global Ethnic Diversity - Asian",
        "Global Ethnic Diversity - Black",
        "Global Ethnic Diversity - Hispanic/Latinx",
        "Global Ethnic Diversity - White",
        "Global Ethnic Diversity - Two or More Races/Other",
        "Global Ethnic Diversity - Did Not Respond/Declined",
        "Board of Directors Ethnic Diversity - Asian",
        "Board of Directors Ethnic Diversity - Black/African American",
        "Board of Directors Ethnic Diversity - White",
        "Operating Committee Ethnic Diversity - Asian",
        "Operating Committee Ethnic Diversity - Black/African American",
        "Operating Committee Ethnic Diversity - Hispanic/Latino",
        "Operating Committee Ethnic Diversity - White",
        "U.S. Employees Ethnic Diversity - American Indian/Alaskan Native",
        "U.S. Employees Ethnic Diversity - Asian",
        "U.S. Employees Ethnic Diversity - Black/African American",
        "U.S. Employees Ethnic Diversity - Hispanic/Latino",
        "U.S. Employees Ethnic Diversity - Native Hawaiian/Pacific Islander",
        "U.S. Employees Ethnic Diversity - Two or More Races",
        "U.S. Employees Ethnic Diversity - White",
        "U.S. Employees Ethnic Diversity - Not Declared",
        "Board Racial/Ethnic Diversity",
        "Racial/Ethnic Diversity in Management",
        "Employee Diversity - U.S. Ethnic Minority",
        "New Employee Hires - U.S. Ethnic Minority",
        "Ethnic Minority Representation",
        "Pay Equity - Minority vs Non-Minority"
    ],
    
    "recordable injury": [
        "Recordable Injury or Illness Rate - Total",
        "Recordable Injury or Illness Rate - Employees",
        "Recordable Injury or Illness Rate - Contractors",
        "Recordable Injury or Illness Rate - Workforce/Combined",
        "Recordable Injury Frequency (RIF)",
        "Total Recordable Incident Rate (TRIR) - Total",
        "Total Recordable Incident Rate (TRIR) - Employees",
        "Total Recordable Incident Rate (TRIR) - Contractors",
        "Total Recordable Incident Rate (TRIR) - Workforce/Combined",
        "Total Recordable Injury Frequency Rate (TRIFR)",
        "Employee Total Recordable Rate",
        "Contractor Total Recordable Rate",
        "Workforce Total Recordable Rate",
        "Total Recordables (Illness) - Employees",
        "Total Recordables (Illness) - Contractors",
        "Total Recordables (Illness) - Employees & Contractors",
        "Total Recordable Fatalities - Illness Related",
        "Total Recordable Fatalities - Injury Related",
        "Recordable Injury Rate per Million Hours Worked"
    ],
    
    "renewable energy": [
        "Renewable Energy - Total",
        "Renewable Energy - Purchased",
        "Renewable Energy - Self-Generated",
        "Renewable Energy Consumed in Facilities",
        "Solar Energy",
        "Hydropower",
        "Wind Energy",
        "Natural Gas",
        "Nonrenewable Energy",
        "Purchased Energy Consumption (Excl. Renewable Energy)",
        "Total Renewable Energy Generated"
    ],
    
    "scope 1 emissions": [
        "Scope 1 Emissions - Total",
        "Scope 1 Emissions - Direct",
        "Scope 1 Emissions - Location-Based",
        "Scope 1 Emissions - Market-Based",
        "Scope 1 Emissions - Operational Control",
        "Scope 1 GHG Emissions - Total",
        "Scope 1 GHG Emissions - CO2",
        "Scope 1 GHG Emissions - Methane (CH4)",
        "Scope 1 GHG Emissions - Nitrous Oxide (N2O)",
        "Scope 1 GHG Emissions - Biogenic",
        "Scope 1 Emissions - Combustion",
        "Scope 1 Emissions - Fugitive",
        "Scope 1 Emissions - Venting",
        "Scope 1 Emissions - Flaring",
        "Scope 1 Emissions - Transportation",
        "Scope 1 Emissions - Power/Heat/Steam Generation",
        "Scope 1 Emissions Intensity",
        "Scope 1 CH4 Emissions Intensity",
        "Scope 1 Emissions - By Business Activity (LNG)",
        "Scope 1 Emissions - By Business Activity (Pipelines)",
        "Scope 1 Emissions - By Business Activity (Exploration & Production)",
        "Scope 1 Emissions - By Business Activity (Refining & Petrochemicals)",
        "Scope 1 Emissions - By Business Activity (Power Generation)",
        "Scope 1 Emissions - By Geography (Russian Entities)",
        "Scope 1 Emissions - By Geography (Foreign Entities)",
        "Scope 1 Emissions - Cell",
        "Scope 1 Emissions - Module",
        "Scope 1 Emissions - Pack",
        "Scope 1 Emissions - Others",
        "Methane as % of Scope 1 Emissions",
        "% of Scope 1 Emissions Covered by Regulation",
        "Scope 1 Emissions Reduction from Initiatives",
        "Scope 1 & 2 Emissions - Total",
        "Scope 1 & 2 Emissions - Market-Based",
        "Scope 1 & 2 Emissions - Location-Based",
        "Scope 1 & 2 Emissions - By Source",
        "Scope 1 & 2 Emissions Intensity",
        "Scope 1 & 2 Emissions - Change vs Base Year",
        "Scope 1 & 2 Emissions - Excluding Power/Steam Not Consumed",
        "Total Energy Consumption (Scope 1 & 2)",
        "Energy Intensity (Scope 1 & 2)"
    ],
    
    "scope 2 emissions": [
        "Scope 2 Emissions - Total",
        "Scope 2 Emissions - Location-Based",
        "Scope 2 Emissions - Market-Based",
        "Scope 2 Emissions - Operational Control",
        "Scope 2 Emissions - Purchased Energy",
        "Scope 2 Emissions - Purchased Electricity",
        "Scope 2 Emissions - Indirect",
        "Scope 2 GHG Emissions - Total",
        "Scope 2 GHG Emissions - Location-Based",
        "Scope 2 GHG Emissions - Market-Based",
        "Scope 2 Emissions - By Business Activity",
        "Scope 2 Emissions - Cell",
        "Scope 2 Emissions - Module",
        "Scope 2 Emissions - Pack",
        "Scope 2 Emissions - Others",
        "Scope 2 Emissions Intensity",
        "Scope 2 Emissions Reduction from Initiatives",
        "Scope 2 Power Acquisition - Location-Based",
        "Scope 2 Power Acquisition - Market-Based",
        "CO2e from Imported Electricity (Scope 2)",
        "Purchased Electricity - Total",
        "Purchased Electricity - Renewable",
        "Purchased Electricity - Non-Renewable",
        "Purchased Electricity from Renewable Sources"
    ],
    
    "scope 3 emissions": [
        "Scope 3 Emissions - Total",
        "Scope 3 Emissions Intensity",
        "Scope 3 Emissions Reduction from Initiatives",
        "Scope 3 GHG Emissions - Total",
        "Scope 3 GHG Emissions - Biogenic",
        "Scope 3 Emissions - Category 1: Purchased Goods and Services",
        "Scope 3 Emissions - Category 2: Capital Goods",
        "Scope 3 Emissions - Category 3: Fuel and Energy-Related Activities",
        "Scope 3 Emissions - Category 4: Upstream Transportation and Distribution",
        "Scope 3 Emissions - Category 5: Waste Generated in Operations",
        "Scope 3 Emissions - Category 6: Business Travel",
        "Scope 3 Emissions - Category 7: Employee Commuting",
        "Scope 3 Emissions - Category 8: Upstream Leased Assets",
        "Scope 3 Emissions - Category 9: Downstream Transportation and Distribution",
        "Scope 3 Emissions - Category 11: Use of Sold Products",
        "Scope 3 Emissions - Category 12: End-of-Life Treatment of Sold Products",
        "Scope 3 Emissions - Category 13: Downstream Leased Assets",
        "Scope 3 Emissions - Category 14: Franchises",
        "Scope 3 Emissions - Category 15: Investments",
        "Scope 3 Emissions - Use of Sold Products (Construction Industries)",
        "Scope 3 Emissions - Use of Sold Products (Energy & Transportation)",
        "Scope 3 Emissions - Use of Sold Products (Resource Industries)",
        "Scope 3 Emissions - Use of Sold Products (Enterprise)",
        "Scope 3 Emissions - Financed Emissions",
        "Scope 3 Emissions - Upstream Oil and Gas Production",
        "Scope 3 Target-Based Intensity"
    ],
    
    "total ghg emissions": [
        "Total Greenhouse Gas Emissions",
        "Total GHG Emissions - Location-Based",
        "Total GHG Emissions - Market-Based",
        "Total GHG Emissions - Net Equity",
        "Total GHG Emissions - By Geography (EMEA)",
        "Total GHG Emissions - By Geography (AMER)",
        "Total GHG Emissions - By Geography (APAC)",
        "Total GHG Emissions - Fleet",
        "Total GHG Emissions - Natural Gas",
        "Total GHG Emissions Intensity"
    ],
    
    "total waste": [
        "Total Waste Generated",
        "Total Hazardous Waste Generated",
        "Total Non-Hazardous Waste Generated",
        "Total Waste Directed to Disposal",
        "Total Waste Diverted from Disposal",
        "Hazardous Waste - Landfill",
        "Hazardous Waste - Incineration with Energy Recovery",
        "Hazardous Waste - Incineration without Energy Recovery",
        "Hazardous Waste - Other Disposal",
        "Hazardous Waste - Reduction",
        "Non-Hazardous Waste - Landfill",
        "Non-Hazardous Waste - Composting",
        "Non-Hazardous Waste - Recycling",
        "Non-Hazardous Waste - Incineration with Energy Recovery",
        "Non-Hazardous Waste - Incineration without Energy Recovery",
        "Total Waste - Landfill",
        "Total Waste - Recycling",
        "Total Waste - Composting",
        "Total Waste - Incineration with Energy Recovery",
        "Total Waste - Incineration without Energy Recovery",
        "Total Waste - Reused",
        "Total Waste - Otherwise Disposed",
        "Total Waste - Recovered (Other Ways)",
        "Total Waste - Neutralization and Disposal",
        "Total Waste - Utilized",
        "Total Waste - Recovery",
        "Waste - Reduction",
        "Waste - To Energy",
        "Waste - Recycled/Reused/Composted Percentage",
        "Waste - Landfilled at Own Facilities Percentage",
        "Waste - By Geography (Russian Entities)",
        "Waste - By Geography (Foreign Entities)",
        "Waste - By Hazard Class and Geography",
        "Waste - By Source (Third Parties)",
        "Waste - Transferred to Third Parties",
        "Waste - Inventory (Beginning)",
        "Waste - Inventory (End)",
        "Waste - Eliminated",
        "Waste - Disposed",
        "General Industrial Solid Waste - Total",
        "General Industrial Solid Waste - Recycled",
        "General Industrial Solid Waste - Landfill",
        "General Industrial Solid Waste - Disposed",
        "General Industrial Solid Waste - Incineration with Energy Recovery",
        "General Industrial Solid Waste - Reused",
        "General Industrial Solid Waste - Recovered (Other Ways)",
        "Waste Generated in Operations - Emissions"
    ],
    
    "total employees": [
        "Total Employees",
        "New Employee Hires - Total",
        "Employee Turnover - Total",
        "Average Training Hours - Total",
        "Employee Training Coverage - Total (%)",
        "Gender Pay Ratio",
        "Employees Entitled to Parental Leave - Total",
        "Employees Who Took Parental Leave - Total",
        "Employees Still Employed 12 Months After Parental Leave Return - Total",
        "Number of Employee Fatalities"
    ],
    
    "volunteering": [
        "Total Volunteer Hours",
        "Number of Employee Volunteers",
        "Occupational Disease Cases"
    ],
    
    "waste recycled": [
        "Total Waste Recycled",
        "Hazardous Waste Recycled",
        "Non-Hazardous Waste Recycled",
        "Solid Waste Recycled Reused and Composted",
        "Percentage of Hazardous Waste Recycled",
        "Percentage of Non-Hazardous Waste Recycled",
        "Percentage of Solid Waste Recycled Reused and Composted",
        "Water Recycling Rate"
    ],
    
    "water consumption": [
        "Total Water Withdrawal",
        "Total Water Consumption",
        "Total Water Usage",
        "Total Water Discharge",
        "Total Freshwater Withdrawal",
        "Total Freshwater Consumption",
        "Water Withdrawal - Groundwater",
        "Water Withdrawal - Surface Water",
        "Water Withdrawal - Municipal Water",
        "Water Withdrawal - Third-Party Water",
        "Water Withdrawal - Seawater",
        "Water Withdrawal - Rainwater",
        "Water Withdrawal - Recycled Water",
        "Water Withdrawal - Other Sources",
        "Water Consumption - Groundwater",
        "Water Consumption - Surface Water",
        "Water Consumption - Municipal Water",
        "Water Consumption - Rainwater",
        "Water Consumption - Recycled Water",
        "Water Consumption - New Water",
        "Water Consumption - In Process",
        "Water Consumption - Concessionaries",
        "Total Water Withdrawal - Water-Stressed Areas",
        "Total Water Consumption - Water-Stressed Areas",
        "Percentage of Water Withdrawal in Water-Stressed Areas",
        "Percentage of Water Consumption in Water-Stressed Areas",
        "Water Consumption Intensity",
        "Conventional Freshwater Consumption",
        "Unconventional Freshwater Consumption",
        "Water Use Reduction"
    ],
    
    "water discharge": [
        "Total Water Discharge",
        "Total Water Discharge - Water-Stressed Areas",
        "Produced Water Discharged Offshore"
    ],
    
    "water recycled": [
        "Total Water Recycled and Reused",
        "Produced Water Recycled or Reused",
        "Municipal Wastewater Reused",
        "Third-Party Recycled Water"
    ],
    
    "women employees": [
        "Total Female Employees",
        "Total Male Employees",
        "Percentage of Female Employees",
        "Percentage of Male Employees"
    ]
}

# Build global catalog from all groups
GLOBAL_STANDARD_NAMES = []
for standards in STANDARD_NAMES_BY_GROUP.values():
    GLOBAL_STANDARD_NAMES.extend(standards)

# Remove duplicates while preserving order
seen = set()
GLOBAL_STANDARD_NAMES = [x for x in GLOBAL_STANDARD_NAMES if not (x in seen or seen.add(x))]

print(f"Loaded {len(STANDARD_NAMES_BY_GROUP)} metric groups")
print(f"Total {len(GLOBAL_STANDARD_NAMES)} unique standard names")