esg_trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: trino
      port: 8080
      database: delta
      schema: default
      threads: 4
      http_scheme: http
      user: trino
